version: '3.9'

services:
  delify-api:
    build:
      context: .
      dockerfile: src/Delify.Api/Dockerfile
    container_name: delify-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Delify=Host=postgres;Port=5432;Database=delify;Username=delify;Password=delify
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
